# ===============================
# Application
# ===============================
spring.application.name=bootrestbook

# ===============================
# DataSource (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/springDB
spring.datasource.username=postgres
spring.datasource.password=Baramati@12
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#entity(table) will be auto created
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
